language: node_js

os:
  - linux
  - osx

node_js: "12.14.1"

services:
  - xvfb

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_BRANCH" == "release" ]]; then sudo apt update && sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib bsdtar rpm libopenjp2-tools; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_BRANCH" == "release" ]]; then brew install rpm; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_BRANCH" == "release" ]]; then electron-builder --linux snap -c.snap.publish=github; fi
  - npx nyc --reporter=lcov npm test && npx codecov
  - if [[ "$TRAVIS_BRANCH" == "release" ]]; then npm run dist; fi

notifications:
  email:
    on_success: never
