language: node_js

os:
  - linux
  - osx

node_js: "7.9.0"


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update && sudo apt-get install -q libxss-dev; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3; fi

script:
  - npm install -g istanbul
  - istanbul cover ./node_modules/mocha/bin/_mocha

notifications:
  email:
    on_success: never

on_failure: change

after_success:
  - bash <(curl -s https://codecov.io/bash)
