os: unstable

platform:
  - x86
  - x64

skip_tags: true

environment:
  nodejs_version: "12.13.0"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm -g
  - npm install

test_script:
  - node --version
  - npm --version
  - npx nyc --reporter=lcov npm test && npx codecov

build_script:
  - IF %APPVEYOR_REPO_BRANCH%==release (npm run dist)
