build: off

os: unstable

platform:
  - x86
  - x64

skip_tags: true

environment:
  nodejs_version: "8.9.3"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm -g
  - npm install
  - npm install -g istanbul

test_script:
  - node --version
  - npm --version
  - istanbul cover .\node_modules\mocha\bin\_mocha

after_test:
  - bash <(curl -s https://codecov.io/bash)
