build: off

os: unstable

platform:
  - x86
  - x64

skip_tags: true

environment:
  nodejs_version: "6.5.0"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm
  - .\node_modules\.bin\npm install

test_script:
  - node --version
  - .\node_modules\.bin\npm --version
  - appveyor-retry call .\node_modules\.bin\npm run test
