os: Visual Studio 2019

platform:
  - x64

skip_tags: true

environment:
  nodejs_version: "16.9.1"

branches:
  only:
    - release

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm -g
  - npm install

build_script:
  - node_modules/.bin/electron-builder build --x64 --ia32
